const M = require('./build_memoire.js');
const { h1, h2, h3, p, rt, caption, table, pageBreak, codeBlock } = M;
const { Paragraph, TextRun, ExternalHyperlink, AlignmentType } = require('docx');

function link(text, url) {
  return new Paragraph({
    spacing: { after: 160 },
    children: [new ExternalHyperlink({
      link: url,
      children: [new TextRun({ text, style: "Hyperlink", color: M.GREEN, underline: {}, size: 21, font: M.FONT })],
    })],
  });
}

const annexes = [
  h1("VII. Annexes"),

  h2("Annexe A : Script SQL complet"),
  p("Le script ci-dessous crée l'intégralité des huit tables de la base de données terre_sana, dans l'ordre imposé par les dépendances de clés étrangères. Il reproduit exactement la structure de la base utilisée par l'application."),
  codeBlock([
    "CREATE DATABASE IF NOT EXISTS terre_sana CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;",
    "USE terre_sana;",
    "",
    "-- Table : admin (héritée du stage)",
    "CREATE TABLE admin (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY,",
    "  username VARCHAR(255) NOT NULL,",
    "  password VARCHAR(255) NOT NULL,",
    "  CONSTRAINT uq_admin_username UNIQUE (username)",
    ");",
    "",
    "-- Table : project (héritée du stage)",
    "CREATE TABLE project (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY, admin_id BIGINT,",
    "  name VARCHAR(255), description VARCHAR(255),",
    "  link VARCHAR(255), documentation_link VARCHAR(255),",
    "  image VARCHAR(255), category VARCHAR(255),",
    "  is_active BOOLEAN DEFAULT TRUE,",
    "  created_at DATETIME(6),",
    "  CONSTRAINT fk_project_admin FOREIGN KEY (admin_id) REFERENCES admin(id)",
    ");",
    "",
    "-- Table : blog_post (héritée du stage)",
    "CREATE TABLE blog_post (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY, admin_id BIGINT,",
    "  title VARCHAR(255), content VARCHAR(5000), image VARCHAR(255),",
    "  is_published BOOLEAN DEFAULT FALSE,",
    "  created_at DATETIME(6),",
    "  CONSTRAINT fk_blogpost_admin FOREIGN KEY (admin_id) REFERENCES admin(id)",
    ");",
    "",
    "-- Table : contact_message (héritée du stage)",
    "CREATE TABLE contact_message (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY, admin_id BIGINT,",
    "  name VARCHAR(255), email VARCHAR(255), message VARCHAR(5000),",
    "  is_read BOOLEAN NOT NULL DEFAULT FALSE,",
    "  created_at DATETIME(6),",
    "  CONSTRAINT fk_contact_admin FOREIGN KEY (admin_id) REFERENCES admin(id)",
    ");",
    "",
    "-- Table : app_users (module TFE)",
    "CREATE TABLE app_users (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY,",
    "  first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL,",
    "  email VARCHAR(200) NOT NULL, password VARCHAR(255) NOT NULL,",
    "  phone VARCHAR(30), birth_date DATE, gender VARCHAR(20),",
    "  city VARCHAR(255), postal_code VARCHAR(20),",
    "  skills TEXT, availability VARCHAR(255),",
    "  preferred_language VARCHAR(5) DEFAULT 'fr',",
    "  level ENUM('BRONZE','ARGENT','OR') NOT NULL DEFAULT 'BRONZE',",
    "  is_active BOOLEAN NOT NULL DEFAULT TRUE,",
    "  reset_token VARCHAR(255), reset_token_expiry DATETIME(6),",
    "  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),",
    "  CONSTRAINT uq_app_users_email UNIQUE (email)",
    ");",
    "",
    "-- Table : events (module TFE)",
    "CREATE TABLE events (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY, admin_id BIGINT,",
    "  title VARCHAR(255) NOT NULL, description TEXT,",
    "  event_date DATETIME(6) NOT NULL, location VARCHAR(300) NOT NULL,",
    "  max_places INT NOT NULL,",
    "  status ENUM('OPEN','FULL','CANCELLED','FINISHED') NOT NULL DEFAULT 'OPEN',",
    "  image_url VARCHAR(500),",
    "  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),",
    "  CONSTRAINT fk_event_admin FOREIGN KEY (admin_id) REFERENCES admin(id)",
    ");",
    "",
    "-- Table : registrations (module TFE)",
    "CREATE TABLE registrations (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY,",
    "  user_id BIGINT NOT NULL, event_id BIGINT NOT NULL, validated_by_id BIGINT,",
    "  status ENUM('WAITING','CONFIRMED','REFUSED') NOT NULL DEFAULT 'WAITING',",
    "  position INT,",
    "  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),",
    "  CONSTRAINT uq_registration_user_event UNIQUE (user_id, event_id),",
    "  CONSTRAINT fk_reg_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,",
    "  CONSTRAINT fk_reg_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,",
    "  CONSTRAINT fk_reg_admin FOREIGN KEY (validated_by_id) REFERENCES admin(id)",
    ");",
    "",
    "-- Table : reviews (module TFE)",
    "CREATE TABLE reviews (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY,",
    "  user_id BIGINT NOT NULL, event_id BIGINT NOT NULL,",
    "  rating INT NOT NULL, comment TEXT,",
    "  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),",
    "  CONSTRAINT chk_review_rating CHECK (rating BETWEEN 1 AND 5),",
    "  CONSTRAINT uq_review_user_event UNIQUE (user_id, event_id),",
    "  CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,",
    "  CONSTRAINT fk_review_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE",
    ");",
    "",
    "-- Index complémentaires : accélèrent les requêtes les plus fréquentes du module",
    "-- (les clés étrangères et contraintes UNIQUE sont déjà indexées automatiquement par MySQL)",
    "CREATE INDEX idx_events_date_location ON events (event_date, location);",
    "  -- Supporte checkNoDuplicate (RG-08), appelée à chaque création/modification d'événement",
    "CREATE INDEX idx_events_status ON events (status);",
    "  -- Supporte le filtrage par statut sur la liste publique des événements",
    "CREATE INDEX idx_registrations_status ON registrations (event_id, status);",
    "  -- Supporte countByEventAndStatus, appelée à chaque affichage des places disponibles",
  ]),
  p("Les index sur les clés étrangères et les colonnes UNIQUE sont créés automatiquement par MySQL et n'apparaissent donc pas explicitement ci-dessus. Les trois index complémentaires ajoutés ciblent précisément les requêtes les plus fréquemment exécutées par le module : idx_events_date_location accélère la vérification de doublon (RG-08), appelée à chaque création ou modification d'événement, et idx_registrations_status accélère le comptage des places disponibles, recalculé à chaque affichage d'un événement plutôt que stocké (section 2.2.3)."),
  pageBreak(),

  h2("Annexe B : Note sur les captures d'écran"),
  p("Les captures d'écran présentées en section 3.4 ont été réalisées en environnement local (localhost), à partir de données de démonstration créées pour les besoins de ce rapport, notamment un compte bénévole de test (« Camille Dupont ») créé via le formulaire d'inscription public pour illustrer l'espace personnel bénévole en conditions réelles plutôt qu'à l'état vide."),

  h2("Annexe C : Dépôt GitHub"),
  p("Le code source complet du site Terra Sana, incluant le module de gestion des bénévoles et des événements, développé dans le cadre de ce TFE, est disponible à l'adresse suivante :"),
  link("https://github.com/sidanne/terra-sana-website", "https://github.com/sidanne/terra-sana-website"),
];

module.exports = { annexes };
