const M = require('./build_memoire.js');
const { h1, h2, h3, p, rt, caption, table, pageBreak, codeBlock } = M;
const { Paragraph, TextRun, ExternalHyperlink, AlignmentType } = require('docx');

function link(text, url) {
  return new Paragraph({
    spacing: { after: 160 },
    children: [new ExternalHyperlink({
      link: url,
      children: [new TextRun({ text, style: "Hyperlink", color: M.GREEN, underline: {}, size: 21, font: M.FONT })],
    })],
  });
}

const annexes = [
  h1("VII. Annexes"),

  h2("Annexe A — Script SQL complet"),
  p("Le script ci-dessous crée l'intégralité des huit tables de la base de données terresana, dans l'ordre imposé par les dépendances de clés étrangères."),
  codeBlock([
    "CREATE DATABASE IF NOT EXISTS terresana CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
    "USE terresana;",
    "",
    "-- Table : admin (héritée du stage)",
    "CREATE TABLE admin (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY,",
    "  username VARCHAR(100) NOT NULL UNIQUE,",
    "  password VARCHAR(255) NOT NULL",
    ");",
    "",
    "-- Table : project (héritée du stage)",
    "CREATE TABLE project (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY,",
    "  name VARCHAR(200) NOT NULL, description TEXT NOT NULL,",
    "  link VARCHAR(500), documentation_link VARCHAR(500),",
    "  image VARCHAR(255), category VARCHAR(255),",
    "  is_active BOOLEAN NOT NULL DEFAULT TRUE, admin_id BIGINT,",
    "  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,",
    "  CONSTRAINT fk_project_admin FOREIGN KEY (admin_id) REFERENCES admin(id)",
    ");",
    "",
    "-- Table : blog_post (héritée du stage)",
    "CREATE TABLE blog_post (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY, admin_id BIGINT,",
    "  title VARCHAR(255) NOT NULL, content TEXT NOT NULL, image VARCHAR(255),",
    "  is_published BOOLEAN NOT NULL DEFAULT FALSE,",
    "  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,",
    "  CONSTRAINT fk_blogpost_admin FOREIGN KEY (admin_id) REFERENCES admin(id)",
    ");",
    "",
    "-- Table : contact_message (héritée du stage)",
    "CREATE TABLE contact_message (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY, admin_id BIGINT NULL,",
    "  name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL,",
    "  message VARCHAR(5000) NOT NULL, is_read BOOLEAN NOT NULL DEFAULT FALSE,",
    "  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,",
    "  CONSTRAINT fk_contact_admin FOREIGN KEY (admin_id) REFERENCES admin(id)",
    ");",
    "",
    "-- Table : app_users (module TFE)",
    "CREATE TABLE app_users (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY,",
    "  first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL,",
    "  email VARCHAR(200) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,",
    "  phone VARCHAR(30), birth_date DATE, gender VARCHAR(20),",
    "  city VARCHAR(255), postal_code VARCHAR(20),",
    "  skills TEXT, availability VARCHAR(255),",
    "  preferred_language VARCHAR(5) NOT NULL DEFAULT 'fr',",
    "  level VARCHAR(10) NOT NULL DEFAULT 'BRONZE',",
    "  is_active BOOLEAN NOT NULL DEFAULT TRUE,",
    "  reset_token VARCHAR(255), reset_token_expiry DATETIME,",
    "  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
    ");",
    "",
    "-- Table : events (module TFE)",
    "CREATE TABLE events (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY, admin_id BIGINT,",
    "  title VARCHAR(255) NOT NULL, description TEXT NOT NULL,",
    "  event_date DATETIME NOT NULL, location VARCHAR(300) NOT NULL,",
    "  max_places INT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'OPEN',",
    "  image_url VARCHAR(500),",
    "  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,",
    "  CONSTRAINT fk_event_admin FOREIGN KEY (admin_id) REFERENCES admin(id)",
    ");",
    "",
    "-- Table : registrations (module TFE)",
    "CREATE TABLE registrations (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY,",
    "  user_id BIGINT NOT NULL, event_id BIGINT NOT NULL, validated_by_id BIGINT,",
    "  status VARCHAR(20) NOT NULL DEFAULT 'WAITING', position INT,",
    "  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,",
    "  CONSTRAINT uq_registration_user_event UNIQUE (user_id, event_id),",
    "  CONSTRAINT fk_reg_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,",
    "  CONSTRAINT fk_reg_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,",
    "  CONSTRAINT fk_reg_admin FOREIGN KEY (validated_by_id) REFERENCES admin(id)",
    ");",
    "",
    "-- Table : reviews (module TFE)",
    "CREATE TABLE reviews (",
    "  id BIGINT AUTO_INCREMENT PRIMARY KEY,",
    "  user_id BIGINT NOT NULL, event_id BIGINT NOT NULL,",
    "  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5), comment TEXT,",
    "  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,",
    "  CONSTRAINT uq_review_user_event UNIQUE (user_id, event_id),",
    "  CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,",
    "  CONSTRAINT fk_review_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE",
    ");",
    "",
    "-- Index complémentaires : accélèrent les requêtes les plus fréquentes du module",
    "-- (les clés étrangères et contraintes UNIQUE sont déjà indexées automatiquement par MySQL)",
    "CREATE INDEX idx_events_date_location ON events (event_date, location);",
    "  -- Supporte checkNoDuplicate (RG-08), appelée à chaque création/modification d'événement",
    "CREATE INDEX idx_events_status ON events (status);",
    "  -- Supporte le filtrage par statut sur la liste publique des événements",
    "CREATE INDEX idx_registrations_status ON registrations (event_id, status);",
    "  -- Supporte countByEventAndStatus, appelée à chaque affichage des places disponibles",
  ]),
  p("Les index sur les clés étrangères et les colonnes UNIQUE sont créés automatiquement par MySQL et n'apparaissent donc pas explicitement ci-dessus. Les trois index complémentaires ajoutés ciblent précisément les requêtes les plus fréquemment exécutées par le module : idx_events_date_location accélère la vérification de doublon (RG-08), appelée à chaque création ou modification d'événement, et idx_registrations_status accélère le comptage des places disponibles, recalculé à chaque affichage d'un événement plutôt que stocké (section 2.2.3)."),
  pageBreak(),

  h2("Annexe B — Note sur les captures d'écran"),
  p("Les captures d'écran présentées en section 3.4 ont été réalisées en environnement local (localhost), à partir de données de démonstration créées pour les besoins de ce rapport — notamment un compte bénévole de test (« Camille Dupont ») créé via le formulaire d'inscription public pour illustrer l'espace personnel bénévole en conditions réelles plutôt qu'à l'état vide."),

  h2("Annexe C — Dépôt GitHub"),
  p("Le code source complet du site Terra Sana, incluant le module de gestion des bénévoles et des événements développé dans le cadre de ce TFE, est disponible à l'adresse suivante :"),
  link("https://github.com/sidanne/terra-sana-website", "https://github.com/sidanne/terra-sana-website"),
];

module.exports = { annexes };
