const M = require('./build_memoire.js');
const { h1, h2, h3, p, rt, bullet, caption, imgPara, table, pageBreak, codeBlock, GREEN } = M;

const SCR = __dirname + '/screenshots/';

const technique = [
  h1("III. Dossier technique"),
  p("Cette section décrit les décisions d'implémentation du module : les choix technologiques et leur justification, l'architecture globale, les principaux écrans avec leur fonctionnement, la sécurité mise en place et l'environnement de développement retenu."),

  h2("3.1. Choix technologiques"),
  p("La pile technique du module TFE s'appuie sur les technologies enseignées dans le cursus (Java, Spring Boot, MySQL), en complément de React déjà utilisé côté frontend depuis le stage. Elle diffère volontairement de certaines stacks JavaScript full-stack plus légères, afin de démontrer la maîtrise d'une architecture Java d'entreprise typique."),

  table(["Composant", "Technologie", "Justification"], [
    ["Framework backend", "Spring Boot 3.5.13 (Java 21)", "Auto-configuration, large écosystème, standard de l'industrie pour les API d'entreprise"],
    ["Accès aux données", "Spring Data JPA / Hibernate", "Abstraction du SQL, requêtes dérivées par convention de nommage, mapping objet-relationnel"],
    ["Sécurité", "Spring Security + jjwt 0.11.5", "Authentification stateless par JWT, adaptée à une SPA React ; deux jetons distincts (RG-25)"],
    ["Hachage des mots de passe", "BCrypt (Spring Security)", "Sel automatique, résistant aux attaques par table arc-en-ciel (RG-02)"],
    ["Base de données", "MySQL 9.1.0", "SGBD relationnel enseigné en cours d'analyse, bonnes pratiques de normalisation"],
    ["Envoi d'e-mails", "Spring Boot Starter Mail (Gmail SMTP)", "Confirmations, relances et notifications automatiques (RG-12, RG-13, RG-20)"],
    ["Génération de PDF", "iText7 7.2.5", "Attestations bénévole et export de la liste des inscrits (RG-21, RG-22)"],
    ["Frontend", "React 18.2.0", "Continuité avec le site développé pendant le stage, composants réutilisables"],
    ["Graphiques", "Chart.js", "Courbe des inscriptions par mois, répartition des statuts sur le tableau de bord"],
    ["Environnement local", "WAMP Server 3.3.7", "Serveur MySQL local sous Windows pour le développement et la démonstration"],
  ], [2100, 2650, 4600]),
  caption("Tableau 9 — Choix technologiques du module TFE"),

  p("La figure ci-dessous illustre cette pile technique par grande couche, chaque bloc étant coloré selon l'identité visuelle usuelle de la technologie qu'il représente."),
  ...imgPara(SCR + "tech_stack.png", 560, 319, "Figure 5 — Pile technique du module, par couche"),

  p("Deux alternatives ont été écartées consciemment. Côté base de données, une solution NoSQL (MongoDB) aurait été envisageable pour sa flexibilité de schéma, mais les données du module (bénévoles, événements, inscriptions) sont fortement relationnelles : une inscription n'a de sens qu'accompagnée d'un bénévole ET d'un événement existants, avec une contrainte d'unicité stricte sur ce couple (RG-09), ce que MySQL exprime nativement via des clés étrangères et une contrainte UNIQUE, là où une base documentaire demanderait de réimplémenter ces garanties manuellement dans le code applicatif. Côté backend, une pile Node.js/Express aurait permis de rester dans un unique langage avec le frontend React, mais Spring Boot a été préféré pour rester cohérent avec les technologies du cursus académique et démontrer une architecture typée de bout en bout, du contrôleur jusqu'à la colonne SQL."),

  p("Le choix de Spring Data JPA plutôt que du JDBC pur ou d'un query builder plus léger se justifie par le volume de requêtes dérivées qu'autorise le module (section 3.2.2) : la majorité des accès aux données du module TFE s'exprime par de simples signatures de méthode, sans SQL manuel, ce qui réduit le risque d'erreur de syntaxe et concentre l'effort de développement sur la logique métier plutôt que sur l'écriture répétitive de requêtes. jjwt a été préféré à une implémentation JWT maison pour la même raison qui justifie BCrypt plutôt qu'un hachage SHA fait main : la cryptographie appliquée ne se réinvente pas, elle s'appuie sur des bibliothèques éprouvées et maintenues. Enfin, iText7 a été retenu pour la génération de PDF plutôt que JasperReports, envisagé un temps : pour des documents au contenu simple (une attestation, une liste tabulaire), iText7 permet un contrôle direct et minimal du contenu généré, sans la couche de templates XML que JasperReports impose pour des rapports plus complexes que ceux réellement nécessaires ici."),

  h2("3.2. Architecture globale"),
  p("Le module repose sur une architecture 3-tiers classique, séparant la couche de présentation (frontend React), la couche métier (API Spring Boot) et la couche de données (MySQL). Chaque module fonctionnel du backend (bénévoles, événements, inscriptions, avis) suit le pattern en couches standard de Spring Boot : un Controller reçoit la requête HTTP, un Service porte la logique métier, un Repository accède aux données via Spring Data JPA."),

  table(["Couche", "Classe type", "Responsabilité"], [
    ["Controller", "EventController, RegistrationController", "Reçoit les requêtes HTTP, délègue au service, retourne la réponse JSON"],
    ["Service", "EventService, RegistrationService", "Logique métier : règles de gestion, calcul de statut, envoi d'emails"],
    ["Repository", "EventRepository, RegistrationRepository", "Interfaces Spring Data JPA, requêtes dérivées et JPQL"],
    ["Model", "Event, Registration, AppUser, Review", "Entités JPA mappées sur les tables MySQL"],
    ["Config / Security", "JwtFilter, JwtUtil, VolunteerJwtUtil, SecurityConfig", "Génération et validation des jetons, règles d'autorisation par endpoint"],
  ], [1900, 3400, 4050]),
  caption("Tableau 10 — Structure en couches du backend Spring Boot"),

  p("La structure des packages reflète cette organisation :"),
  codeBlock([
    "com.terresana.backend",
    "├── controller/   AuthController, AppUserController, EventController,",
    "│                 RegistrationController, ReviewController,",
    "│                 ProjectController, BlogPostController, ContactController",
    "├── service/      AppUserService, EventService, RegistrationService,",
    "│                 ReviewService, EmailService, PdfService,",
    "│                 EventImageService, ProjectImageService",
    "├── repository/   AppUserRepository, EventRepository,",
    "│                 RegistrationRepository, ReviewRepository, ...",
    "├── model/        Admin, AppUser, Event, Registration, Review, ...",
    "│   └── enums/    EventStatus, RegistrationStatus, Level",
    "├── config/       SecurityConfig, JwtFilter, JwtUtil,",
    "│                 VolunteerJwtUtil, GlobalExceptionHandler",
    "└── BackendApplication.java",
  ]),
  p("Côté frontend, chaque page (Events.js, VolunteerDashboard.js, Admin.js…) consomme l'API REST via un service HTTP dédié (services/volunteerApi.js pour l'espace bénévole, services/api.js pour le site vitrine), et le token JWT courant est géré centralement dans services/auth.js."),

  h3("3.2.1. Contrôle de la sérialisation JSON"),
  p("L'entité AppUser illustre un point d'attention systématique du module : ne jamais laisser une information sensible transiter par erreur dans une réponse API, même de façon indirecte. Deux annotations Jackson y sont utilisées à dessein plutôt qu'une seule, pour deux besoins différents :"),
  codeBlock([
    "@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)",
    "private String password;   // acceptable en entrée (inscription), jamais renvoyé",
    "",
    "@JsonIgnore",
    "private String resetToken; // ni en entrée, ni en sortie : jamais exposé au client",
  ]),
  p("Le mot de passe utilise WRITE_ONLY et non @JsonIgnore, car @JsonIgnore aurait aussi bloqué la désérialisation du champ envoyé par le formulaire d'inscription : le mot de passe doit rester acceptable en entrée tout en étant systématiquement omis des réponses JSON. Le jeton de réinitialisation, à l'inverse, n'a jamais besoin d'être envoyé par le client : @JsonIgnore l'exclut complètement, empêchant qu'il puisse fuiter dans une réponse API et permettre une prise de compte."),

  h3("3.2.2. Requêtes dérivées Spring Data JPA"),
  p("Spring Data JPA permet de définir une requête simplement en nommant la méthode selon une convention précise, sans écrire la moindre ligne de SQL ou de JPQL : Spring génère l'implémentation à partir du nom lui-même. RegistrationRepository en est une illustration directe, chaque méthode correspondant à un besoin métier précis du module :"),
  codeBlock([
    "public interface RegistrationRepository extends JpaRepository<Registration, Long> {",
    "",
    "    // Vérifier si un bénévole est déjà inscrit à un événement (RG-09)",
    "    Optional<Registration> findByUserAndEvent(AppUser user, Event event);",
    "",
    "    // Compter les places prises (CONFIRMED) pour savoir si l'événement est plein",
    "    long countByEventAndStatus(Event event, RegistrationStatus status);",
    "",
    "    // Liste d'attente triée par date d'inscription (le plus ancien passe en premier)",
    "    List<Registration> findByEventAndStatusOrderByCreatedAtAsc(Event event, RegistrationStatus status);",
    "}",
  ]),
  p("Le nom findByEventAndStatusOrderByCreatedAtAsc se lit littéralement comme la règle qu'il implémente : trouver les inscriptions d'un événement (By Event), dont le statut correspond (And Status), triées par date de création croissante (OrderBy CreatedAt Asc), c'est-à-dire exactement la liste d'attente dans l'ordre d'arrivée nécessaire à RG-13, sans qu'une seule ligne de logique de tri n'ait été écrite manuellement."),

  h3("3.2.3. Intégrations externes et traitement planifié"),
  p("Le module n'appelle aucune API externe à l'exécution : les photos associées aux événements (section 3.3.2) proviennent d'une table de correspondance fixe d'URL Unsplash déjà vérifiées, choisies localement par mots-clés, et non d'un appel réseau à un service tiers : un choix qui évite toute dépendance de disponibilité envers un service externe pour une fonctionnalité aussi secondaire qu'une image d'illustration. Le seul service externe réellement sollicité est le serveur SMTP de Gmail, pour l'envoi des e-mails (section 3.3.5)."),
  p("Le module comporte en revanche un traitement planifié : une tâche @Scheduled de Spring, exécutée automatiquement toutes les cinq minutes, fait basculer en FINISHED tout événement encore marqué OPEN ou FULL dont la date est désormais dépassée (RG-06). Sans ce mécanisme, un événement resté OPEN après son déroulement continuerait, par exemple, à accepter de nouvelles inscriptions ou à autoriser un avis prématuré, en contradiction avec RG-07 et RG-16."),
  codeBlock([
    "// Bascule automatiquement en FINISHED tout événement OPEN/FULL dont la date est",
    "// passée. Tourne toutes les 5 minutes ; CANCELLED n'est jamais touché (décision",
    "// explicite de l'administrateur uniquement).",
    "@Scheduled(fixedRate = 300000)",
    "public void autoMarkFinishedEvents() {",
    "    List<Event> toFinish = eventRepo.findByEventDateBeforeAndStatusIn(",
    "            LocalDateTime.now(), List.of(EventStatus.OPEN, EventStatus.FULL));",
    "    if (!toFinish.isEmpty()) {",
    "        toFinish.forEach(e -> e.setStatus(EventStatus.FINISHED));",
    "        eventRepo.saveAll(toFinish);",
    "    }",
    "}",
  ]),
  p("Le choix d'un intervalle de cinq minutes, plutôt qu'un calcul à la demande à chaque affichage, tient à la sémantique même du statut FINISHED : contrairement au nombre de places disponibles (section 2.2.3), qui doit toujours refléter l'instant présent, le passage à FINISHED déclenche des effets de bord (ouverture du dépôt d'avis RG-16, éligibilité à l'attestation RG-21) qu'il est plus sûr de matérialiser explicitement en base à intervalles réguliers plutôt que de recalculer silencieusement à chaque lecture."),

  h2("3.3. Fonctionnalités transversales notables"),
  p("Quatre mécanismes, moins visibles qu'un écran mais représentatifs des choix d'implémentation retenus, méritent d'être détaillés : la gestion centralisée des erreurs, l'attribution automatique d'une photo aux événements et projets, l'envoi asynchrone des e-mails, et l'architecture retenue pour l'interface multilingue."),

  h3("3.3.1. Gestion centralisée des erreurs (GlobalExceptionHandler)"),
  p("Sans mécanisme dédié, une erreur métier levée dans un service Spring (email déjà utilisé, mot de passe incorrect, inscription déjà existante...) se traduit par défaut par une erreur 500 générique côté client, sans que le message clair écrit dans le service n'atteigne jamais le frontend. GlobalExceptionHandler intercepte, au niveau de l'application entière, toute RuntimeException levée par un contrôleur ou un service, et la transforme systématiquement en réponse HTTP 400 structurée :"),
  codeBlock([
    "@RestControllerAdvice",
    "public class GlobalExceptionHandler {",
    "    @ExceptionHandler(RuntimeException.class)",
    "    public ResponseEntity<Map<String, String>> handle(RuntimeException e) {",
    "        return ResponseEntity.status(HttpStatus.BAD_REQUEST)",
    "                .body(Map.of(\"message\", e.getMessage()));",
    "    }",
    "}",
  ]),
  p("Ce choix centralise en un seul endroit une responsabilité qui, sans lui, devrait être dupliquée dans chaque contrôleur (bloc try/catch autour de chaque appel de service). C'est ce mécanisme qui permet, par exemple, au frontend d'afficher directement le message « Un événement existe déjà le [date] à [lieu]. » renvoyé par EventService lorsqu'un doublon RG-08 est détecté, plutôt qu'un message d'erreur générique."),

  h3("3.3.2. Attribution automatique des photos (EventImageService)"),
  p("L'administrateur de Terra Sana ne dispose généralement pas d'une URL d'image sous la main au moment de créer un événement ou un projet. Plutôt que d'afficher une image par défaut identique pour toutes les activités, EventImageService (et son équivalent ProjectImageService) recherche des mots-clés dans le titre et la description de l'événement, et associe la première catégorie thématique correspondante à une photo Unsplash déjà vérifiée. Une quarantaine de catégories sont couvertes (cuisine, distribution alimentaire, sport, formation, nettoyage, marché bio, etc.)."),
  p("Deux détails d'implémentation évitent les faux positifs les plus fréquents : le mot-clé « don » est volontairement exclu au profit de « dons »/« don alimentaire », car « don » est un sous-mot de l'adverbe très courant « donc » ; et « distribution » seul est trop générique (distribution de magazines n'a rien à voir avec de la nourriture), d'où la restriction à « distribution alimentaire ». Lorsqu'une catégorie propose plusieurs photos, la variante retenue est choisie de façon stable, et non aléatoire, via un hachage du texte complet, afin qu'un même événement affiche toujours la même image d'un rechargement à l'autre, tout en répartissant les événements d'une même catégorie sur plusieurs visuels différents :"),
  codeBlock([
    "private String pickVariant(List<String> options, String rawText) {",
    "    if (options.size() == 1) return options.get(0);",
    "    int index = Math.floorMod(rawText.hashCode(), options.size());",
    "    return options.get(index);",
    "}",
  ]),
  p("Ce mécanisme reste une heuristique par mots-clés, et non une reconnaissance d'image : un champ URL manuel permet à l'administrateur de le remplacer pour tout événement au sujet réellement inédit."),

  h3("3.3.3. Calcul du niveau de fidélité (updateLevel)"),
  p("La méthode updateLevel d'AppUserService recalcule le niveau du bénévole après chaque événement affectant le nombre de ses participations confirmées, aussi bien une nouvelle confirmation qu'une désinscription qui en fait perdre une. Le niveau n'est donc jamais figé une fois atteint : il reflète à tout instant le nombre réel de participations confirmées (RG-19)."),
  codeBlock([
    "public void updateLevel(AppUser user, long confirmedCount) {",
    "    Level oldLevel = user.getLevel();",
    "    Level newLevel = confirmedCount >= 7 ? Level.OR",
    "                    : confirmedCount >= 3 ? Level.ARGENT",
    "                    : Level.BRONZE;",
    "    user.setLevel(newLevel);",
    "    userRepo.save(user);",
    "    // L'email n'est envoyé qu'en cas de progression réelle, jamais sur une baisse",
    "    if (newLevel.ordinal() > oldLevel.ordinal()) {",
    "        emailService.sendLevelChange(user, newLevel.name());",
    "    }",
    "}",
  ]),
  p("Le détail qui mérite d'être souligné porte sur l'envoi de l'e-mail de félicitations (RG-20) : la comparaison newLevel.ordinal() > oldLevel.ordinal() garantit que ce message n'est déclenché qu'en cas de progression effective. Sans cette vérification, un bénévole dont le niveau redescendrait d'ARGENT à BRONZE après une désinscription recevrait, par erreur, le même e-mail de félicitations qu'une réelle promotion : un cas limite qui n'apparaît pas dans une lecture rapide de la règle de gestion, mais que le code met en évidence."),

  h3("3.3.4. Génération des attestations PDF (PdfService)"),
  p("La génération des attestations et des exports de liste d'inscrits repose sur iText7, utilisé en mode « bas niveau » (construction directe de paragraphes et de tableaux) plutôt que via un système de templates, pour un contenu qui reste volontairement simple. Le contrôle d'accès à l'attestation, déjà appliqué côté contrôleur, est revérifié une seconde fois à l'intérieur même du service, avant toute génération du document :"),
  codeBlock([
    "// Génère l'attestation uniquement si la participation est confirmée et l'événement terminé",
    "public byte[] generateAttestation(AppUser user, Event event, Registration registration) {",
    "    if (registration.getStatus() != RegistrationStatus.CONFIRMED) {",
    "        throw new RuntimeException(\"Attestation disponible uniquement pour une \" +",
    "            \"participation confirmée.\");",
    "    }",
    "    if (event.getStatus() != EventStatus.FINISHED) {",
    "        throw new RuntimeException(\"Attestation disponible uniquement après \" +",
    "            \"la fin de l'événement.\");",
    "    }",
    "    // ... construction du document PDF (iText7)",
    "}",
  ]),
  p("Cette double vérification (RG-21) illustre un principe déjà rencontré en section 3.5.3 pour le mot de passe : toute règle de gestion touchant à une action sensible est revérifiée au plus près de l'exécution réelle, plutôt que déléguée à un unique point de contrôle en amont. La charte graphique du site est reprise jusque dans le document PDF lui-même : l'attestation utilise la même couleur verte (RGB 45, 106, 79) que l'interface, via la classe DeviceRgb d'iText7."),

  h3("3.3.5. Envoi asynchrone des e-mails (EmailService)"),
  p("Le module envoie automatiquement un e-mail à chaque étape clé du parcours bénévole : confirmation d'inscription, refus, promotion depuis la liste d'attente, changement de niveau, annulation d'un événement, message groupé de l'administrateur, réinitialisation de mot de passe. Toutes ces méthodes sont annotées @Async : l'aller-retour SMTP réel peut prendre une à trois secondes, un délai qui serait perceptible et bloquant s'il fallait l'attendre avant de répondre à la requête HTTP qui l'a déclenché. Grâce à @Async, le contrôleur retourne sa réponse (par exemple la confirmation d'une inscription) immédiatement, pendant que l'envoi de l'e-mail se poursuit sur un thread séparé, géré par le pool de tâches asynchrones de Spring."),

  h3("3.3.6. Interface multilingue (FR / EN / NL)"),
  p("Chaque page du frontend, y compris l'ensemble du tableau de bord administrateur, définit un objet de traduction T = { fr: {...}, en: {...}, nl: {...} }, et récupère les textes affichés via t = T[lang] || T.fr, où lang est transmis depuis le sélecteur de langue de la barre de navigation jusqu'à chaque route dans App.js. Les libellés variables (par exemple « 3 places restantes sur 5 ») passent par des fonctions plutôt que par du texte figé, afin de rester grammaticalement corrects dans les trois langues :"),
  codeBlock([
    "placesRemaining: (n, max) => `${n} places restantes sur ${max}`,",
    "// ...",
    "remaining: (n, max) => `${n} of ${max} spots left`,",
  ]),
  p("Les données propres à Terra Sana (titres d'événements, descriptions saisies par l'administrateur) ne sont volontairement pas traduites automatiquement : seule l'interface elle-même (labels, boutons, messages de succès ou d'erreur) l'est, ce qui évite d'introduire une dépendance à un service de traduction externe pour du contenu géré par l'association elle-même."),

  h3("3.3.7. Pagination et filtres avancés"),
  p("Les listes d'événements et de bénévoles côté administrateur reposent sur l'interface Pageable de Spring Data JPA plutôt que sur un chargement complet suivi d'une pagination côté client : chaque appel à /api/events/paged ou /api/volunteers/paged précise un numéro de page et une taille, et seule la page demandée est effectivement extraite de la base de données. Ce choix évite de transférer l'intégralité des bénévoles ou des événements passés à chaque ouverture du tableau de bord, un point qui deviendra sensible si Terra Sana accumule plusieurs années d'historique d'événements."),
  p("Le filtrage des bénévoles par compétence, disponibilité et langue (section 3.4.6, onglet Bénévoles) combine plusieurs conditions optionnelles dans une même requête JPA : lorsque l'administrateur laisse un champ de filtre vide, la condition correspondante est simplement omise plutôt que comparée à une chaîne vide, afin de retourner l'ensemble des bénévoles quand aucun critère n'est renseigné."),

  h3("3.3.8. Graphiques du tableau de bord (Chart.js)"),
  p("L'onglet Statistiques du tableau de bord administrateur affiche deux visualisations construites avec Chart.js à partir des données réelles de l'association : une courbe (Line) du nombre d'inscriptions par mois sur les six derniers mois, et un diagramme en anneau (Doughnut) répartissant les inscriptions entre CONFIRMED, WAITING et REFUSED, permettant de visualiser en un coup d'œil le taux de participation global. Ces deux graphiques sont recalculés côté frontend à chaque chargement, à partir des inscriptions récupérées via l'API : aucune agrégation statistique n'est pré-calculée ni stockée côté serveur, ce qui garantit que les chiffres affichés reflètent toujours l'état courant de la base."),

  h2("3.4. Présentation des interfaces"),
  p("Cette section présente les principaux écrans du module, tels qu'implémentés, avec une capture d'écran et une explication fonctionnelle pour chacun."),

  h3("3.4.1. Page d'accueil"),
  p("La page d'accueil met en avant le prochain événement à venir, les statistiques de l'association (bénévoles actifs, événements organisés, applications internes), la mission de Terra Sana, un parcours en trois étapes pour devenir bénévole, les prochains événements et le hub des douze applications internes héritées du stage."),
  ...imgPara(SCR + "home.png", 580, 362, "Figure 6 — Bandeau d'accueil du site Terra Sana"),

  h3("3.4.2. Inscription et connexion bénévole"),
  p("Un visiteur crée un compte bénévole via un formulaire dédié : nom, prénom, email et mot de passe sont obligatoires (marqués d'un badge « ? »), les autres champs (téléphone, ville, compétences, disponibilités, langue préférée) restent facultatifs, conformément au principe de minimisation des données. Une fois le compte créé, le bénévole se connecte via un jeton JWT distinct de celui de l'administrateur (RG-25)."),
  ...imgPara(SCR + "volunteer-register.png", 480, 480, "Figure 7 — Formulaire de création de compte bénévole"),
  ...imgPara(SCR + "volunteer-login.png", 580, 362, "Figure 8 — Écran de connexion bénévole"),
  ...imgPara(SCR + "forgot-password.png", 580, 362, "Figure 9 — Réinitialisation du mot de passe bénévole"),

  h3("3.4.3. Espace personnel bénévole"),
  p("Après connexion, le bénévole accède à son espace personnel : profil avec badge de niveau (Bronze / Argent / Or, RG-19), compétences déclarées, statistiques de participation, progression vers le niveau suivant, informations personnelles modifiables, prochains événements auxquels il est inscrit et historique de participation exportable en PDF."),
  ...imgPara(SCR + "volunteer-dashboard.png", 580, 362, "Figure 10 — Espace personnel d'un bénévole nouvellement inscrit"),

  h3("3.4.4. Liste des événements"),
  p("La page publique des événements affiche l'ensemble des activités à venir sous forme de cartes (photo, statut, date, lieu, places restantes) ainsi qu'une section « Événements passés » distincte, avec le statut TERMINÉ ou ANNULÉ. Chaque carte permet de s'inscrire directement en un clic. Une fois l'inscription envoyée, la carte affiche immédiatement un retour visuel : confirmation d'envoi, puis rappel que le bénévole est déjà inscrit et en attente de validation par l'administrateur."),
  ...imgPara(SCR + "events-list.png", 580, 362, "Figure 11 — Liste publique des événements Terra Sana (extrait)"),
  ...imgPara(SCR + "dashboard-registrations-tab.png", 580, 362, "Figure 12 — Retour visuel après une demande d'inscription (RG-10, RG-11)"),

  h3("3.4.5. Parcours complet d'un bénévole"),
  p("Pour donner une vision d'ensemble cohérente des écrans présentés séparément ci-dessus, cette section retrace le parcours complet d'un bénévole, de sa première visite jusqu'à l'obtention de son attestation, en reliant chaque étape à l'écran et à la règle de gestion qui la régissent."),
  table(["Étape", "Écran / action", "Règle(s) de gestion associées"], [
    ["1", "Le visiteur consulte la liste des événements sans être connecté", "Consultation publique"],
    ["2", "Il crée un compte via le formulaire d'inscription (nom, email, mot de passe)", "RG-01, RG-02"],
    ["3", "Il se connecte et arrive sur son espace personnel, niveau BRONZE par défaut", "RG-19"],
    ["4", "Il s'inscrit à un événement ; si celui-ci est complet, il est placé en liste d'attente", "RG-09, RG-10"],
    ["5", "Il reçoit un e-mail automatique confirmant son inscription ou sa mise en attente", "RG-12"],
    ["6", "L'administrateur confirme l'inscription depuis le tableau de bord", "RG-11"],
    ["7", "Le jour de l'événement passé, son statut passe à FINISHED", "RG-06"],
    ["8", "Le bénévole laisse un avis noté (1 à 5) sur l'événement", "RG-15 à RG-18"],
    ["9", "Sa participation confirmée fait progresser son compteur de niveau", "RG-19, RG-20"],
    ["10", "Il télécharge son attestation de participation au format PDF", "RG-21"],
  ], [900, 5500, 2050]),
  caption("Tableau 11 — Parcours complet d'un bénévole, du premier contact à l'attestation"),

  h3("3.4.6. Tableau de bord administrateur"),
  p("Le tableau de bord administrateur, accessible uniquement au rôle ADMIN (RG-24), centralise la gestion opérationnelle du module. Dix onglets organisent cette gestion, répartis en trois groupes dans la barre latérale : Principal (tableau de bord, événements, bénévoles, inscriptions, retours post-événement), Rapports (attestations PDF, statistiques) et Site vitrine (projets, blog, messages, ces trois derniers hérités du site développé pendant le stage). Les sous-sections suivantes détaillent chacun des écrans propres au module TFE, avec une capture d'écran réelle et son fonctionnement."),

  p("La page d'accueil du tableau de bord affiche une vue synthétique de l'activité : quatre indicateurs clés (bénévoles actifs, événements à venir, inscriptions en attente, taux de participation), la liste des prochains événements avec leur taux de remplissage, et des raccourcis vers les actions les plus fréquentes."),
  ...imgPara(SCR + "admin-dashboard.png", 580, 362, "Figure 13 — Tableau de bord administrateur : vue d'ensemble"),

  p("L'onglet Événements réunit, sur un même écran, le formulaire de création (titre, lieu, description, date, capacité maximale) et la liste des événements existants, avec pour chacun un sélecteur de statut manuel (utile pour une annulation, RG-06) et des actions rapides : voir les inscrits, voir les avis, envoyer un email groupé, modifier ou supprimer. La capture ci-dessous montre le formulaire rempli pour un événement de démonstration, juste avant sa création."),
  ...imgPara(SCR + "admin-events-create-filled.png", 580, 362, "Figure 14 — Création d'un événement depuis le tableau de bord"),

  p("L'onglet Inscriptions centralise, tous événements confondus, la validation manuelle exigée par RG-11 : chaque ligne affiche le bénévole, l'événement concerné et son statut, avec deux boutons Confirmer / Refuser directement disponibles pour toute inscription encore WAITING."),
  ...imgPara(SCR + "admin-registrations.png", 580, 362, "Figure 15 — Suivi et validation des inscriptions (RG-11)"),

  p("L'onglet Bénévoles liste l'ensemble des comptes inscrits, avec leur niveau de fidélité (RG-19), leur statut actif/inactif et un bouton de désactivation conforme à RG-03 (le compte est neutralisé, jamais supprimé, pour préserver son historique). Trois filtres (compétence, disponibilité, langue) permettent à l'administrateur de cibler rapidement un profil recherché pour un événement particulier."),
  ...imgPara(SCR + "admin-volunteers.png", 580, 362, "Figure 16 — Liste et filtrage des bénévoles"),

  p("L'onglet Statistiques restitue graphiquement, via Chart.js (section 3.3.8), l'évolution des inscriptions sur les six derniers mois et la répartition des statuts d'inscription, pour une lecture immédiate de l'activité de l'association qu'aucun fichier Excel ne permettait auparavant (section 1.3)."),
  ...imgPara(SCR + "admin-statistics.png", 580, 362, "Figure 17 — Statistiques du tableau de bord (Chart.js)"),

  p("Enfin, l'onglet Attestations PDF liste les bénévoles éligibles à une attestation de participation (c'est-à-dire ceux dont l'inscription est CONFIRMED à un événement déjà FINISHED, RG-21), à titre indicatif pour l'administrateur : chaque bénévole télécharge lui-même son propre document depuis son espace personnel (section 3.4.3)."),
  ...imgPara(SCR + "admin-attestations.png", 580, 362, "Figure 18 — Suivi des attestations éligibles (RG-21)"),

  h3("3.4.7. Pages institutionnelles et interface multilingue"),
  p("Les pages du site vitrine hérité du stage (À propos, Contact, Aide/FAQ…) ont été redessinées avec la nouvelle charte graphique et restent, elles aussi, entièrement traduites en trois langues, y compris les questions fréquentes, comme l'illustre la capture ci-dessous, prise après bascule du sélecteur de langue sur l'anglais."),
  ...imgPara(SCR + "about.png", 580, 362, "Figure 19 — Page « À propos » de Terra Sana"),
  ...imgPara(SCR + "contact.png", 580, 362, "Figure 20 — Formulaire de contact"),
  ...imgPara(SCR + "aide-en.png", 580, 362, "Figure 21 — Page d'aide affichée en anglais, après changement de langue"),
  p("Les pages Sponsors et Bénévolat complètent la vitrine institutionnelle : la première présente les partenaires qui soutiennent Terra Sana (Bruxelles Environnement, la Région de Bruxelles, la commune de Woluwe-Saint-Lambert), la seconde constitue le point d'entrée principal vers la création d'un compte bénévole pour un nouveau visiteur."),
  ...imgPara(SCR + "sponsors.png", 580, 362, "Figure 22 — Page des sponsors et partenaires"),
  ...imgPara(SCR + "benevolat.png", 580, 362, "Figure 23 — Page de présentation du bénévolat"),

  h2("3.5. Sécurité"),
  p("La sécurité du module s'appuie sur Spring Security et une authentification JWT entièrement stateless : aucune session n'est conservée côté serveur, chaque requête porte sa propre preuve d'identité dans l'en-tête HTTP Authorization."),

  h3("3.5.1. Deux jetons distincts (RG-25)"),
  p("Conformément à RG-25, les bénévoles et l'administrateur reçoivent chacun un jeton signé avec un secret distinct (JwtUtil pour l'admin, VolunteerJwtUtil pour le bénévole), tous deux valables 24 heures (RG-23). Le filtre JwtFilter tente successivement les deux JwtUtil lors de la validation d'une requête et assigne le rôle ROLE_ADMIN ou ROLE_VOLUNTEER en conséquence : le rôle n'est pas un claim porté par le jeton lui-même, il est déduit de la clé de signature qui a permis de le valider. Ce filtre, exécuté une seule fois par requête (OncePerRequestFilter), s'intercale avant le filtre d'authentification standard de Spring Security :"),
  codeBlock([
    "protected void doFilterInternal(HttpServletRequest request,",
    "        HttpServletResponse response, FilterChain chain) {",
    "    String header = request.getHeader(\"Authorization\");",
    "    if (header != null && header.startsWith(\"Bearer \")) {",
    "        String token = header.substring(7);",
    "        // Admin et bénévole utilisent des clés secrètes distinctes : on essaie les deux",
    "        if (jwtUtil.validateToken(token)) {",
    "            authenticate(jwtUtil.extractUsername(token), \"ROLE_ADMIN\");",
    "        } else if (volunteerJwtUtil.validateToken(token)) {",
    "            authenticate(volunteerJwtUtil.extractUsername(token), \"ROLE_VOLUNTEER\");",
    "        }",
    "    }",
    "    chain.doFilter(request, response);",
    "}",
  ]),

  h3("3.5.2. Autorisation par endpoint"),
  p("La configuration Spring Security (SecurityConfig) définit explicitement, endpoint par endpoint et par méthode HTTP, les routes publiques, celles réservées au rôle ADMIN, et celles ouvertes à tout jeton valide (chaque contrôleur vérifiant alors lui-même l'identité exacte, par exemple pour n'autoriser un bénévole à annuler que sa propre inscription)."),
  table(["Portée", "Endpoint", "Règle"], [
    ["Public", "POST /api/volunteers/register", "Inscription (RG-01)"],
    ["Public", "POST /api/volunteers/login, forgot-password, reset-password", "Authentification bénévole"],
    ["Public", "GET /api/events, /api/events/*", "Consultation des événements (visiteur)"],
    ["Public", "GET /api/projects, /api/posts", "Site vitrine hérité du stage"],
    ["Public", "GET /api/reviews/event/*", "Moyenne des avis affichée publiquement"],
    ["Public", "POST /api/contact", "Formulaire de contact"],
    ["Jeton bénévole", "GET/PUT /api/volunteers/me", "Consultation et modification du profil"],
    ["Jeton bénévole", "GET /api/volunteers/me/attestation/*", "Téléchargement d'attestation (RG-21)"],
    ["Réservé ADMIN", "POST/PUT/DELETE /api/events/**", "Gestion des événements (RG-24)"],
    ["Réservé ADMIN", "PUT /api/registrations/*/confirm, /reject", "Validation des inscriptions (RG-11, RG-24)"],
    ["Réservé ADMIN", "GET /api/volunteers, /api/volunteers/paged", "Liste et filtres des bénévoles"],
    ["Réservé ADMIN", "PUT /api/volunteers/*/toggle-active", "Activation / désactivation (RG-03)"],
    ["Réservé ADMIN", "POST /api/registrations/event/*/group-email", "Envoi d'un email groupé"],
    ["Jeton valide (bénévole ou admin)", "Le reste des endpoints", "Identité exacte vérifiée dans le contrôleur"],
  ], [2200, 4300, 2650]),
  caption("Tableau 12 — Règles d'autorisation par endpoint (SecurityConfig)"),
  codeBlock([
    ".authorizeHttpRequests(auth -> auth",
    "    .requestMatchers(HttpMethod.POST, \"/api/volunteers/register\").permitAll()",
    "    .requestMatchers(HttpMethod.GET, \"/api/events\", \"/api/events/*\").permitAll()",
    "    .requestMatchers(HttpMethod.POST, \"/api/events\").hasRole(\"ADMIN\")",
    "    .requestMatchers(HttpMethod.PUT, \"/api/registrations/*/confirm\").hasRole(\"ADMIN\")",
    "    .requestMatchers(\"/**\").permitAll()  // le contrôleur vérifie l'identité exacte",
    ")",
    ".addFilterBefore(jwtFilter, UsernamePasswordAuthenticationFilter.class);",
  ]),

  h3("3.5.3. Hachage des mots de passe et validation côté serveur"),
  p("Les mots de passe ne sont jamais stockés en clair : BCryptPasswordEncoder les hache à l'inscription et vérifie l'authenticité à la connexion, avec un sel intégré automatiquement (RG-02). La longueur minimale de 8 caractères imposée par RG-02 est vérifiée deux fois : une première fois côté frontend (attribut minLength du formulaire, pour un retour immédiat à l'utilisateur), et une seconde fois, indépendamment, côté backend dans AppUserService, car un attribut HTML n'empêche en rien un appel direct à l'API contournant le formulaire :"),
  codeBlock([
    "public AppUser register(AppUser user) {",
    "    if (userRepo.existsByEmail(user.getEmail())) {",
    "        throw new RuntimeException(\"Un compte existe déjà avec cet email.\");",
    "    }",
    "    if (user.getPassword() == null || user.getPassword().length() < 8) {",
    "        throw new RuntimeException(\"Le mot de passe doit contenir au moins 8 caractères.\");",
    "    }",
    "    user.setPassword(passwordEncoder.encode(user.getPassword()));",
    "    user.setLevel(Level.BRONZE);",
    "    return userRepo.save(user);",
    "}",
  ]),
  p("Ce principe, ne jamais faire confiance à la seule validation du navigateur, est appliqué systématiquement dans les services du module, chaque règle de gestion touchant à une donnée saisie par l'utilisateur étant revérifiée côté serveur avant toute écriture en base."),

  h3("3.5.4. Configuration CORS"),
  p("La configuration CORS est appliquée globalement au niveau de Spring Security lui-même (et pas seulement via l'annotation @CrossOrigin), afin que les réponses 401/403 générées par Security elle-même portent également les en-têtes CORS attendus par le navigateur."),

  h2("3.6. Environnement de développement et de démonstration"),
  p("Conformément au plan de travail validé avec Madame Namur, l'application est développée et présentée en environnement local, via WAMP Server sous Windows (Apache, MySQL, PHP côté outillage local) : aucun déploiement en ligne (type Railway ou Vercel) n'est prévu dans le cadre de ce TFE. Ce choix permet de concentrer l'effort sur la qualité de l'analyse, la conformité aux bonnes pratiques et la robustesse fonctionnelle du module, plutôt que sur la configuration d'une infrastructure cloud."),
  p("Le code source est versionné sur GitHub tout au long du développement (dépôt indiqué en Annexe C), avec des commits réguliers documentant chaque étape plutôt qu'un unique commit final. Cette discipline de commit fréquent s'est révélée particulièrement utile après un incident survenu en cours de projet : un outil de migration automatisée a un jour remisé (git stash) l'ensemble des modifications non commitées du backend sans prévenir, ce qui aurait pu faire disparaître plusieurs jours de travail si les changements avaient été accumulés dans un unique commit prévu en fin de journée plutôt que validés au fil de l'eau. L'incident, documenté plus en détail en section 4.2, a renforcé la rigueur apportée au versionnement pour le reste du développement."),
  p("Le panneau de contrôle WAMP Server ci-dessous confirme les trois services requis actifs en local (Apache, MySQL, PHP) ainsi que l'accès à phpMyAdmin, l'outil utilisé tout au long du développement pour créer, inspecter et corriger la base de données."),
  ...imgPara(SCR + "wamp_home.png", 580, 326, "Figure 24 — Panneau de contrôle WAMP Server, services actifs"),
  p("La capture suivante montre la structure réelle de la base terre_sana telle qu'observée dans phpMyAdmin au moment de la rédaction de ce rapport : huit tables, conformes au diagramme de classes (section 2.2.1) et au dictionnaire de données (section 2.2.2), sans écart entre le modèle documenté et la base effectivement utilisée par l'application."),
  ...imgPara(SCR + "phpmyadmin_structure.png", 580, 326, "Figure 25 — Structure de la base terre_sana dans phpMyAdmin (huit tables)"),

  h3("3.6.1. Mise en route locale"),
  p("Reproduire l'environnement de démonstration ne nécessite que WAMP Server, Node.js et un IDE Java. Les étapes suivantes permettent de lancer le module depuis une copie du dépôt GitHub (Annexe C) :"),
  table(["Étape", "Commande / action"], [
    ["1. Base de données", "Démarrer WAMP Server, créer la base terre_sana via phpMyAdmin, exécuter le script de l'Annexe A"],
    ["2. Configuration backend", "Renseigner application.properties : URL JDBC, identifiants MySQL, secrets JWT, identifiants Gmail SMTP"],
    ["3. Démarrage backend", "mvn spring-boot:run depuis le dossier backend/ ; API disponible sur http://localhost:8080"],
    ["4. Démarrage frontend", "npm install puis npm start depuis le dossier frontend/ ; application sur http://localhost:3000"],
    ["5. Compte administrateur", "Un compte admin est inséré directement en base (table admin) pour la première connexion"],
  ], [2300, 6950]),
  caption("Tableau 13 — Étapes de mise en route de l'environnement local"),

  h3("3.6.2. Vérification et tests manuels"),
  p("En l'absence de suite de tests automatisés (limite reconnue en section 4.3), la conformité de chaque règle de gestion a été vérifiée manuellement, directement dans le navigateur, à chaque étape significative du développement : création d'un événement à une date et un lieu déjà utilisés pour confirmer le rejet attendu (RG-08), inscription à un événement complet pour vérifier le placement en liste d'attente (RG-10), désinscription d'un bénévole confirmé pour observer la promotion automatique du suivant (RG-13), et bascule systématique entre les trois langues de l'interface pour s'assurer qu'aucun texte ne restait figé en français après un changement de langue."),
  p("Cette démarche, bien que manuelle, a permis d'identifier et de corriger plusieurs anomalies avant la rédaction de ce rapport, notamment un premier jet de la règle RG-08 qui ne comparait que le titre et l'horaire exacts des événements, insuffisant pour détecter un doublon portant un intitulé différent au même lieu et à la même date, corrigé après qu'un contre-exemple concret a mis le problème en évidence."),
  p("Le tableau ci-dessous reprend un échantillon représentatif des scénarios rejoués manuellement, sélectionnés pour couvrir un cas nominal et un cas limite pour chacun des groupes de règles de gestion les plus sensibles."),
  table(["Scénario testé", "Résultat attendu", "Résultat constaté"], [
    ["Créer un événement à une date et un lieu déjà utilisés par un autre événement, avec un titre différent", "Rejet avec message précisant la date et le lieu en conflit (RG-08)", "Conforme"],
    ["S'inscrire deux fois de suite au même événement avec le même compte", "Rejet : contrainte d'unicité (RG-09)", "Conforme"],
    ["S'inscrire à un événement dont toutes les places CONFIRMED sont prises", "Placement automatique en liste d'attente, position calculée (RG-10)", "Conforme"],
    ["Confirmer une inscription en attente alors que l'événement vient d'atteindre sa capacité maximale entretemps", "Rejet explicite, aucun dépassement de capacité (section 2.3)", "Conforme"],
    ["Désinscrire un bénévole CONFIRMED alors qu'un autre bénévole est en liste d'attente", "Promotion automatique du premier en attente, email envoyé (RG-13)", "Conforme"],
    ["Laisser un avis sur un événement dont le statut n'est pas encore FINISHED", "Rejet (RG-16)", "Conforme"],
    ["Laisser un second avis sur un événement déjà noté par le même bénévole", "Rejet : contrainte d'unicité (RG-17)", "Conforme"],
    ["Appeler un endpoint réservé à l'administrateur avec un jeton bénévole valide", "Refus d'accès (RG-24)", "Conforme"],
    ["Changer la langue de l'interface pendant la consultation du tableau de bord administrateur", "Bascule immédiate de l'ensemble des libellés, sans perte de contexte", "Conforme"],
  ], [3550, 3550, 2250]),
  caption("Tableau 14 — Échantillon des scénarios de vérification manuelle rejoués avant remise du rapport"),
  pageBreak(),
];

module.exports = { technique };
