spring.datasource.url=jdbc:mysql://localhost:3306/terre_sana
spring.datasource.username=root
spring.datasource.password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alaintchouapi@gmail.com
spring.mail.password=tlll wvac fhts slid
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true